### ISSUE TITLE
Audio tracking issue

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#10]
- [ ] Audio codecs (50%)
  - [x] Raw PCM
  - [x] ADPCM
  - [x] MP3
  - [ ] Speex
  - [ ] Nellymoser
- [ ] Event sounds (25%)
  - [ ] Start/stop/event sync
  - [ ] Loops
  - [ ] Sound envelopes
- [ ] Stream sounds (15%)
  - [ ] Sync with animation
  - [ ] Sync multiple stream sounds?
 - [ ] ActionScript sounds
   - [ ] Start/stop
   - [ ] Position info
   - [ ] Panning

**Comment by XXLuigiMario** [comment]
Test case for Nollymoser audio: https://cache.armorgames.com/files/games/turret-defense-619.swf

**Comment by XXLuigiMario** [comment]
Test case for Nellymoser audio: https://cache.armorgames.com/files/games/turret-defense-619.swf
