### ISSUE TITLE
Development and tracking issue for `BitmapData.pixelDissolve`.

### ISSUE THREAD

**Issue by iwannabethedev** [ruffle-rs/ruffle#10962]
Brief: `BitmapData.pixelDissolve` may be a more complicated method to figure out how to reverse engineer and implement. This issue is meant to help both coordinate and track its implementation and test.

Thanks and credit to @Dinnerbone and others for their main work as part of figuring out this issue.

### Reverse engineering

API descriptions:
- https://open-flash.github.io/mirrors/as2-language-reference/flash/display/BitmapData.html#pixelDissolve()
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BitmapData.html#pixelDissolve()

(Warning: The example for AVM1 appears correct, while the example for AVM2 appears wrong, given that it does not appear to use the returned random seed).

On why the method might be challenging to reverse-engineer (reading at least the first article is recommended):

- https://fabiensanglard.net/fizzlefade/index.php
- http://antirez.com/news/113
- https://web.archive.org/web/20081217091012/http://www.quasimondo.com/archives/000681.php

In particular, it might well be desirable to achieve pixel accuracy, such that it is not only visual similarity that is achieved, but the same values that are generated for the same input between the official Flash player and Ruffle. This might be challenging to figure out, in particular since the implementation most likely uses some slightly involved algorithmic approach to ensure good performance, such as linear feedback shift register (to visit each pixel at most once).

See the below comments for the main resources and findings on this topic.

### Tasks

Testing:

- [x] Correct number of pixels are changed for different inputs.
- [x] Same image as `src` and `dst`.
- [x] Different image as `src` and `dst`.
- [x] Different colors (how does it handle alpha?).
- [x] Transparent `src` onto opaque `dst`.
- [x] Transparent `src` onto transparent `dst`.
- [x] What happens if the sizes of the images do not fit? Other similar dimensional testing?
- [ ] Performance testing? (Maybe just one basic test with a semi-large image).
- [x] Testing both AVM1 and AVM2 (the API descriptions are very similar, so the behavior might be the same, though this is not certain).

**Comment by iwannabethedev** [comment]
Findings on prior open-source art, based on discussions elsewhere and https://github.com/ruffle-rs/ruffle/wiki/Helpful-Resources#similar-projects (**please be careful that any source code you find is appropriately licensed**):

### https://github.com/openfl/openfl
I found an implementation of BitmapData.noise(), but I did not find any implementation of BitmapData.pixelDissolve().
https://github.com/openfl/openfl/blob/fb02f020003735f8985a353400ae32209052f9d3/src/openfl/display/BitmapData.hx#L2622

### https://github.com/arahaya/CanvasScript3
It appears to have an implementation:
https://github.com/arahaya/CanvasScript3/blob/master/src/cs3/display/BitmapData.js#L755
However, it might not be the right one:
https://web.archive.org/web/20081217091012/http://www.quasimondo.com/archives/000681.php
That link claims that the official Flash player uses the linear feedback shift register, as also written about here:
http://antirez.com/news/113
https://fabiensanglard.net/fizzlefade/index.php

### No mention of BitmapData.pixelDissolve() found
https://github.com/lightspark/lightspark
https://github.com/adobe/avmplus/

### BitmapData.pixelDissolve() appears to be stubbed but not implemented
hhttps://[github.com/awayfl/](http://github.com/awayfl/)
https://github.com/mltframework/swfdec
Gnash: http://git.savannah.gnu.org/cgit/gnash.git
https://github.com/mozilla/shumway

### Other I have trouble searching through
https://github.com/swf2js/swf2js and https://github.com/Next2D, the main code might have been placed in branches.

**Comment by iwannabethedev** [comment]
Related issue (just for AVM1, this issue is for both AVM1 and AVM2): https://github.com/ruffle-rs/ruffle/issues/290 .

**Comment by iwannabethedev** [comment]
I am 99.99% confident that at least for a 10x10 bitmap image, that the algorithm used is indeed linear feedback shift register, and that it happens to use the specific "taps"-value listed at https://en.wikipedia.org/wiki/Linear-feedback_shift_register#Example_polynomials_for_maximal_LFSRs for 8-bit/255-period.

**Comment by iwannabethedev** [comment]
It appears that, at least for AVM2/AS3+, this API description:

> 	numPixels:int (default = 0) — The default is 1/30 of the source area (width x height). 

is false, in my tests against the official Flash Player, `numPixels == 0` results in zero pixels being written, apart from the pixel at `(0, 0)` always being written.

**Comment by iwannabethedev** [comment]
Apparently, Flash Player is arguably buggy if the dimensions of the `BitmapData` has `width` or `height` set to 1. I will try not to emulate that arguable bug, and instead let the implementation be correct also for those cases.

**Comment by iwannabethedev** [comment]
It appears that, when writing to transparency, whatever is there is overwritten.
