### ISSUE TITLE
DisplayObject masking tracking issue

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#17]
- [x] Read clip depths in PlaceObject tags
 - [x] Rendering
   - [x] Desktop
   - [x] Web
 - [x] AVM1 `movieClip.setMask`
 - [ ] AVM2 `displayObject.mask`

**Comment by jcward** [comment]
Just some samples from [strongbad email - dragon](https://xnode.org/archive/homestar/Strong%20Bad%20Email%20058%20-%20Dragon.swf) (a truly important piece of history :smile:), where a presumed mask appears as a "red object":

Text / other objects that are supposed to appear (should be pure `#F00`, my GIF encoder made it ugly)

![test2](https://user-images.githubusercontent.com/2192439/63116030-dbaa3080-bf55-11e9-8509-184bf843d81e.gif)

I'm not sure what the green background is about - though it's a weird "reflection effect":

![image](https://user-images.githubusercontent.com/2192439/63116219-4d827a00-bf56-11e9-8770-f4754f8e199c.png)

Sometimes the transform doesn't seem to align:

![Selection_999(4919)](https://user-images.githubusercontent.com/2192439/63115865-68a0ba00-bf55-11e9-8639-9b7cff6c61aa.png)

**Comment by larsiusprime** [comment]
Some of these artifacts are almost certainly masking effects

**Comment by Herschel** [comment]
Added initial masking support in #57. There is room for improvement still (web canvas backend is not very optimized).

**Comment by kmeisthax** [comment]
This is a bit of a nitpick, but I've noticed that shapes in Homestar Runner files tend to be slightly underfilled compared to Flash. This results in pixel-wide outlines of transparent pixels all over the place, as you can see here:

![Screen Shot 2019-09-29 at 5 50 27 PM](https://user-images.githubusercontent.com/108736/70747536-7983f100-1ce5-11ea-9520-b13b2b537268.png)

This effect is less noticeable at higher resolutions/DPIs, and I'm not sure what causes it.

**Comment by Herschel** [comment]
That looks like #26, which is a limitation of SVG renderers compared to Flash. SVG doesn't antialias perfectly abutting paths in a nice way, and unfortunately this is how Flash exports every shape to avoid overdraw.

That will all go away when we switch to a WebGL backend by default, but unfortunately I think we're stuck with it in the canvas backend.

**Comment by adrian17** [comment]
Seems like Achievement Unlocked uses masks quite extensively, to the extent that:

- on desktop, you get a warning `Too many masks active for stencil buffer; possibly incorrect rendering` - and indeed, the achievement list rendering is incorrect:

![2020-02-27_19-58-49](https://user-images.githubusercontent.com/4729533/75478857-edf23600-599e-11ea-99f9-e7783ed0b4f5.png)

- on web, achievement list rendering is better, but performance is getting absolutely tanked by pushing and popping of masks.
