### ISSUE TITLE
Actionscript Tracking: ContextMenuItem

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#247]
This is the tracking issue for **ContextMenuItem** in AVM1. We will check off each item of progress as appropriate, and fill in any relevant or missing information as we continue development of Ruffle.
# Legend
Each checkbox is independent of another. It's entirely possible for something to be tested but not exist yet, or for us to believe that it's completely functional but we haven't made enough tests to prove it.
#x "Property Exists"
Txis means the item exists, but may not necessarily be fully implemented.
## "Has Test Coverage"
This means that we believe that we have a good test coverage of this item, regardless of if those tests pass. It's okay to have tests available but not implement the item yet.
## "Completely Functional"
This means we believe that the item is completely implemented, and no more work needs to be done towards making it functional.

# ContextMenuItem
### `ContextMenuItem(caption, callbackFunction, separatorBefore, enabled, visible)`
- [x] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional

# Properties
## `caption : String`
- [x] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `enabled : Boolean`
- [x] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `separatorBefore : Boolean`
- [x] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `visible : Boolean`
- [x] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional

### `copy()`
- [x] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `onSelect(obj, menuItem)`
- [x] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional

**Comment by adrian17** [comment]
Closing, as despite this not being usable on all platforms yet, the Actionscript plumbing is fully ready now.
(rationale: if this issue _was_ to wait for all platforms, that'd mean it'd also need to be reopened if we added a new platform without it, which sounds silly)
