### ISSUE TITLE
Actionscript Tracking: ExtendedKey

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#252]
This is the tracking issue for **ExtendedKey** in AVM1. We will check off each item of progress as appropriate, and fill in any relevant or missing information as we continue development of Ruffle.
# Legend
Each checkbox is independent of another. It's entirely possible for something to be tested but not exist yet, or for us to believe that it's completely functional but we haven't made enough tests to prove it.
## "Property Exists"
This means the item exists, but may not necessarily be fully implemented.
## "Has Test Coverage"
This means that we believe that we have a good test coverage of this item, regardless of if those tests pass. It's okay to have tests available but not implement the item yet.
## "Completely Functional"
This means we believe that the item is completely implemented, and no more work needs to be done towards making it functional.

# ExtendedKey
### `SOFT1 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT2 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT3 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT4 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT5 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT6 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT7 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT8 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT9 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT10 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT11 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `SOFT12 : String`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

**Comment by Dinnerbone** [comment]
Closing for now as this is only Flash Lite, and accidentally snuck into the documentation.
