### ISSUE TITLE
Actionscript Tracking: System.capabilities

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#278]
This is the tracking issue for **System\.capabilities** in AVM1. We will check off each item of progress as appropriate, and fill in any relevant or missing information as we continue development of Ruffle.
# Legend
Each checkbox is independent of another. It's entirely possible for something to be tested but not exist yet, or for us to believe that it's completely functional but we haven't made enough tests to prove it.
## "Property Exists"
This means the item exists, but may not necessarily be fully implemented.
## "Has Test Coverage"
This means that we believe that we have a good test coverage of this item, regardless of if those tests pass. It's okay to have tests available but not implement the item yet.
## "Completely Functional"
This means we believe that the item is completely implemented, and no more work needs to be done towards making it functional.

# System\.capabilities
### `hasAudio : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasMP3 : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasAudioEncoder : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasVideoEncoder : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasIME : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `screenResolutionX : Number`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `screenResolutionY : Number`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `screenDPI : Number`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `screenColor : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `pixelAspectRatio : Number`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasAccessibility : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `input : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `isDebugger : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `language : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `manufacturer : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `os : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `serverString : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `version : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasPrinting : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `playerType : String`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasStreamingAudio : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasScreenBroadcast : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasScreenPlayback : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasStreamingVideo : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `hasEmbeddedVideo : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `avHardwareDisable : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `localFileReadDisable : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional
### `windowlessDisable : Boolean`
- [X] Property Exists
- [x] Has Test Coverage
- [x] Completely Functional

**Comment by Dinnerbone** [comment]
All of these are correctly hooked up, even if they're not yet entirely configurable or giving the right value to Ruffle itself.

**Comment by Korne127** [comment]
These properties aren't completely correct. The "input" property exists neither in flash nor in ruffle and should probably be removed. And this issue is missing the cpuAddressSize, cpuArchitecture, hasTLS, isEmbeddedInAcrobat, maxLevelIDC, supports32BitProcesses and supports64BitProcesses properties (which are not in the specs, but have been added in later flash player versions and exist in AVM1).

Also, I don't understand why this is closed and everything was checked. While the attributes are existing (except cpuAddressSize) and stubbed, they don't return the correct results yet, which isn't completely functional.
I think that checking everything is dangerous because it makes you lose track of what's actually implemented and what still needs to be done.
