### ISSUE TITLE
Actionscript Tracking: flash.external.ExternalInterface

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#291]
This is the tracking issue for **flash\.external\.ExternalInterface** in AVM1. We will check off each item of progress as appropriate, and fill in any relevant or missing information as we continue development of Ruffle.
# Legend
Each checkbox is independent of another. It's entirely possible for something to be tested but not exist yet, or for us to believe that it's completely functional but we haven't made enough tests to prove it.
## "Property Exists"
This means the item exists, but may not necessarily be fully implemented.
## "Has Test Coverage"
This means that we have believe that we have a good test coverage of this item, regardless of if those tests pass. It's okay to have tests available but not implement the item yet.
## "Completely Functional"
This means we believe that the item is completely implemented, and no more work needs to be done towards making it functional.

# flash\.external\.ExternalInterface
### `available : Boolean`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `addCallback(methodName, instance, method)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `call(methodName, parameter1)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `_addCallback()`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

**Comment by ROBERT-MCDOWELL** [comment]
Apparently the return of ExternalInterface.cal() does not work. Is it related to _addCallback() method not yet implemented?
exemple:
let jsCall = ExternalInterface.call("jsFunc",obj);
on JS side:
function jsFunc(obj){
    return {test:"ok",cmd:"hello"}
}

the result of jsCall is always null....

**Comment by Aprimez** [comment]
How do I get addCallback working in the js? I tried document.getElementById("rufflePlayer").asFunctionName(param); but that doesn't work and I get an error saying the function doesn't exist. @Dinnerbone @Herschel

**Comment by ROBERT-MCDOWELL** [comment]
you must use the ID of the swf itself, not rufflePlayer element.
