### ISSUE TITLE
Actionscript Tracking: flash.net.FileReferenceList

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#308]
This is the tracking issue for **flash\.net\.FileReferenceList** in AVM1. We will check off each item of progress as appropriate, and fill in any relevant or missing information as we continue development of Ruffle.
# Legend
Each checkbox is independent of another. It's entirely possible for something to be tested but not exist yet, or for us to believe that it's completely functional but we haven't made enough tests to prove it.
## "Property Exists"
This means the item exists, but may not necessarily be fully implemented.
## "Has Test Coverage"
This means that we have believe that we have a good test coverage of this item, regardless of if those tests pass. It's okay to have tests available but not implement the item yet.
## "Completely Functional"
This means we believe that the item is completely implemented, and no more work needs to be done towards making it functional.

# flash\.net\.FileReferenceList
### `_listeners : Array`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `broadcastMessage()`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `fileList : Array`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

### `FileReferenceList()`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `browse(typelist)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `addListener(listener)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional
### `removeListener(listener)`
- [ ] Property Exists
- [ ] Has Test Coverage
- [ ] Completely Functional

**Comment by ROBERT-MCDOWELL** [comment]
bump

**Comment by ROBERT-MCDOWELL** [comment]
It would be so nice to implement this class!!! I developed 15 years ago a super nice file manager to upload and download files, preview, etc.... I passed so much time on it. bug free....

**Comment by SuchAFuriousDeath** [comment]
@ROBERT-MCDOWELL Can you check with latest master? I implemented it in https://github.com/ruffle-rs/ruffle/pull/23889

**Comment by ROBERT-MCDOWELL** [comment]
my filemanager is loading well, but I cannot upload any multiple files since the browse event stil not working.

**Comment by SuchAFuriousDeath** [comment]
I think you need FileReferenceList in avm2, right? This issue (and my implementation in #23889) was avm1-only.

**Comment by ROBERT-MCDOWELL** [comment]
yes but also in avm1. my filemanager is in full AVM1

**Comment by SuchAFuriousDeath** [comment]
Ok then I don't understand what exactly is not working? What browse event are you talking about?

**Comment by kjarosh** [comment]
@ROBERT-MCDOWELL Can you file a separate issue and tag @SuchAFuriousDeath ? This issue is meant for tracking progress.

**Comment by ROBERT-MCDOWELL** [comment]
@kjarosh I can comment on the concerned PR is it ok?

**Comment by kjarosh** [comment]
Sure, but it's better to track issues in issues (that's what they are for). And if you provide reproduction steps and describe the issue, other engineers can take a look at it as well.

**Comment by ROBERT-MCDOWELL** [comment]
I shared my info on discord several times so they are free to ask me an access to my server as the swf cannot be used out of it or I must change all my source code.

**Comment by ROBERT-MCDOWELL** [comment]
btw I can finance some of you who are ready to take a look on it thanks.
