### ISSUE TITLE
Tracking issue for the web example page

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#4]
This is a tracking issue for improvements to the example/test page for the web frontend:
https://github.com/ruffle-rs/ruffle/blob/master/web/packages/demo/www/index.html

* [x] Load local SWFs
* [x] Include remote sample SWFs
  * [x] Get permission from authors
  * [x] Animations
  * [x] Games
* [x] Player UI
  * [x] Play/pause button
  * [x] Fullscreen button
* [ ] Debugging UI
  * [ ] Tree view of SWF tags?
  * [ ] Display all library symbols?
  * [ ] Tree view of display list?
  * [ ] Trace of AS execution?

**Comment by wizzwizz4** [comment]
The URL's changed to https://github.com/ruffle-rs/ruffle/blob/master/web/demo/www/index.html.

**Comment by relrelb** [comment]
The URL's changed to: https://github.com/ruffle-rs/ruffle/blob/master/web/packages/demo/www/index.html.
