### ISSUE TITLE
AVM1 exceptions (throw & catch) tracking issue

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#731]
Going by the newgrounds archive as a reference, about 1.8% _(1696 / 94136)_ of movies contained `throw ...;`. I suspect that number may be inflated by use of the newgrounds API library.

This issue can be split up into some different tasks:
- [x] Support throwing user-exceptions in AVM1 (`Action::Throw`)
- [x] Support `try { ... } catch { ... } finally { ... }` (`Action::Try`)
- [x] Implement a proper `avm1::Error` type that can support user-errors
- [x] Remove all of the existing ways that we throw errors, when they should be silent failures
- [x] Implement a way to always get an  `Object` for `Value`, to allow `Value::Undefined` to be used as an object (this helps with the last point)
- [x] Implement `Error` (#251)

The error type should probably look something like this:
```rust
enum Error<'gc> {
    UserError(Value<'gc>),
    StackOverflow,
    ScriptAborted,
}
```

To my knowledge, there shouldn't be any way to throw exceptions from builtins, and the only way to stop execution is by user code, a variant of stack overflow (recursive prototypes, recursive functions), or a script taking too long and the user being prompted to abort.

Today, we throw lots and lots of errors that we shouldn't. We've been fixing them as we go but this is a systematic thing. Where we do things like `value.as_object()?` we should be returning `Value::Undefined` which itself can be accessed as an object. This could also properly solve value boxing, as that needs to be done ad-hoc today but I suspect would be broken if accessed via our builtins or anywhere else that we retrieve values.

As reference material, here are the top 20 users of `Action::Throw` in the newgrounds archive:

Movie | Throw count
------- | ------------
[political_death_match202c.swf](https://www.newgrounds.com/portal/view/508826/) | 66
[znax202c.swf](https://www.newgrounds.com/portal/view/546877/) | 66
[ButterflyArkanoid202c.swf](https://www.newgrounds.com/portal/view/529122/) | 52
[Stick_stealer202c.swf](https://www.newgrounds.com/portal/view/479014/) | 28
[moshi_puzzle_challenge202c.swf](https://www.newgrounds.com/portal/view/457141/) | 27
[moshi_puzzle_challenge2202c.swf](https://www.newgrounds.com/portal/view/494403/) | 26
[BallToss9202c.swf](https://www.newgrounds.com/portal/view/435333/) | 23
[NgNekoSagaACatsTalecomplet202c.swf](https://www.newgrounds.com/portal/view/517052/) | 21
[bushido_solitaire202c.swf](https://www.newgrounds.com/portal/view/333915/) | 18
[gameik202c.swf](https://www.newgrounds.com/portal/view/378427/) | 18
[DKNH_Phonebook202c.swf](https://www.newgrounds.com/portal/view/417433/) | 18
[fishquestdist202c.swf](https://www.newgrounds.com/portal/view/420098/) | 17
[game202c.swf](https://www.newgrounds.com/portal/view/437267/) | 17
[FairyTreasure202c.swf](https://www.newgrounds.com/portal/view/469910/) | 17
[wedding_dress_up_2010202c.swf](https://www.newgrounds.com/portal/view/548319/) | 17
[pretty_barbie_dress_up202c.swf](https://www.newgrounds.com/portal/view/548324/) | 17
[harry_potter_7_clothes202c.swf](https://www.newgrounds.com/portal/view/553339/) | 17
[imago_game202c.swf](https://www.newgrounds.com/portal/view/511965/) | 15
[On_The_Run_From_A_Mugger_o202c.swf](https://www.newgrounds.com/portal/view/554052/) | 12
[crazydigger_ch1_Secure202c.swf](https://www.newgrounds.com/portal/view/611644/) | 12
